version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  test:
    environment:
      MAVEN_OPTS: -Xmx3200m
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          keys:
            - spring-search-{{ checksum "pom.xml" }}
            - spring-search-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: spring-search-{{ checksum "pom.xml" }}
      - run: mvn test
      - store_artifacts:
          path:  ~/project/target/test-results
      - persist_to_workspace:
          root: ~/project/target
          paths:
            - test-results
  upload_cov:
    docker:
      - image: circleci/node:9.6.1
    steps:
      - attach_workspace:
          at: ~/project/target
      - codecov/upload:
          file: ~/project/target/test-results/coverage/jacoco/jacoco.xml
          flags: coverage
          upload_name: Coverage

workflows:
  version: 2
  test:
    jobs:
      - test
      - upload_cov:
          requires:
            - test
